steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - script: |
      echo Installing packages
      yarn
      echo Install electron app dependencies
      yarn postinstall
      echo Start building MacOS application
      yarn build:mac
      echo MacOS build is complete
    displayName: "Build MacOS app"

  - script: |
      cd dist
      ls
    displayName: "Validate build"

  - task: CopyFiles@2
    inputs:
      sourceFolder: $(Build.SourcesDirectory)/dist
      contents: |
        *.dmg
        *.zip
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: "Copying files"

  - task: PublishPipelineArtifact@0
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: mac
    displayName: "Publish pipeline artifact"
